version: '2'
services:
        scrapper:
                build:
                        context: scrapper
                depends_on:
                        - postgres
        postgres:
                image: postgres
                environment:
                        POSTGRES_PASSWORD: postgres
